name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 89.108.98.146
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/zhar-ptica
            git pull origin main
            npm install
            npm run build